### ISSUE TITLE
:gulpConstantDev FAILED

### ISSUE THREAD

**Issue by mleneveut** [jhipster/jhipster-app#1]
Some tasks (Compile, Java server, BrowserSync) fail with the message : :gulpConstantDev FAILED

Package task fails with the message : gulpBuildWithOpts FAILED

Everything works fine when launched with IntelliJ (Make, run App.java, package with gradlew, ...)

I'm under Windows 7

**Comment by jdubois** [comment]
Do you have a stacktrace also?

**Comment by mleneveut** [comment]
No, nothing else :/

**Comment by jdubois** [comment]
Can you share your `.yo-rc.json` file (change the package name, etc to keep data anonymous)

**Comment by mleneveut** [comment]
{
  "generator-jhipster": {
    "baseName": "myapp",
    "packageName": "mydom.myapp",
    "packageFolder": "mydom.myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": true,
    "rememberMeKey": "mykey",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhipsterVersion": "3.4.0",
    "serverPort": "8080",
    "applicationType": "monolith",
    "jhiPrefix": "jhi",
    "nativeLanguage": "fr",
    "languages": [
      "en",
      "fr"
    ]
  }
}

![image](https://cloud.githubusercontent.com/assets/3854415/18053616/a9821306-6e00-11e6-80c4-bc9c36399a76.png)

**Comment by mleneveut** [comment]
if I change grunt to gulp, I have this error when Compile : 

:bower
:cleanResources UP-TO-DATE:nodeSetup
:gulpConstantDev
SKIPPED
FAILED
BUILD FAILED
Total time: 14.564 secs

**Comment by jdubois** [comment]
Oh you have an issue here... JHipster 3, using Grunt? That's not possible...

**Comment by jdubois** [comment]
Yes but if you switch to Gulp, and re-generate the app, does it work from the command line?

**Comment by mleneveut** [comment]
Nevermind, I was missing the module gulp-replace on this computer, everything works now :)

The app just lacks of logs to identify the root cause.

**Comment by jdubois** [comment]
Yes, but here it's the Gradle logs... Thanks for the feedback, it's great to see the app working!
