### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by jskipgit** [jhipster/jhipster-app#2]
I downloaded onto my mac, when I run I get the security question.  I allow.  Then a few seconds later it quits.  Where should I look for logs?  ...and by the way, as an Instructor, this has some huge potential!! Very excited to use. Regards.

**Comment by jdubois** [comment]
Are you sure it's not running in the background? When you say it quit, did you see it appear in the tray, and did you click on it somewhere?
I'm seeing quite a lot of people using it on Mac, so maybe it depends on your env: do you have specific Mac OS X version (an old one)?

**Comment by jskipgit** [comment]
I am running a brand new MacPro with all OS updates applied.. when i run it
.. i see it show up for a few second in tray... then it disappears.. "ps
-ef |grep JHip" shows it's still running:

 /Applications/JHipsterApp.app/Contents/Frameworks/JHipsterApp
Helper.app/Contents/MacOS/JHipsterApp Helper --type=gpu-process
--channel=14103.0.2074388758
--mojo-application-channel-token=9565444B5A006DFA96E93A77FBC47D68
--no-sandbox --supports-dual-gpus=false
--gpu-driver-bug-workarounds=16,21,25,36,47,50,51,55,57,65,66,72,75
--gpu-vendor-id=0x8086 --gpu-device-id=0x162b --gpu-driver-vendor
--gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086
--gpu-active-device-id=0x162b

**Comment by jskipgit** [comment]
actually.. there are 2 processes running.. i missed the first:

501 14103     1   0 10:51AM ??         0:00.79
/Applications/JHipsterApp.app/Contents/MacOS/JHipsterApp

  501 14147 14103   0 10:51AM ??         0:00.11
/Applications/JHipsterApp.app/Contents/Frameworks/JHipsterApp
Helper.app/Contents/MacOS/JHipsterApp Helper --type=gpu-process
--channel=14103.0.2074388758
--mojo-application-channel-token=9565444B5A006DFA96E93A77FBC47D68
--no-sandbox --supports-dual-gpus=false
--gpu-driver-bug-workarounds=16,21,25,36,47,50,51,55,57,65,66,72,75
--gpu-vendor-id=0x8086 --gpu-device-id=0x162b --gpu-driver-vendor
--gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086
--gpu-active-device-id=0x162b

**Comment by ruddell** [comment]
@jskipgit Did you check the icon bar at the top of the screen (next to Wifi, Bluetooth, etc)?  When I first opened it I didn't know anything happened but it was up there.

**Comment by jskipgit** [comment]
..... and publish to the world that you're idiot in  3.....2......1....  lol .. thanks @ruddell I totally missed that.   Move along people.. nothing to see here
